name: BuyNodes
main: me.jophestus.buynodes.BuyNodes
version: 1.2
depend: [Vault]
author: JOPHESTUS
commands:
    buynode:
        description: Buy a node
        aliases: [buynodes]
        permission: buynodes.buy

